/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "border-default": "#253044",
          "success": "#34D399",
          "inverse-primary": "#bac3ff",
          "primary": "#7C9CFF",
          "on-primary-container": "#f4f2ff",
          "primary-fixed-dim": "#bac3ff",
          "on-secondary": "#ffffff",
          "pink-bg": "#3B1730",
          "border-light": "#1F2937",
          "on-tertiary-fixed-variant": "#793000",
          "surface-container": "#182234",
          "on-secondary-fixed": "#410004",
          "on-tertiary": "#ffffff",
          "surface-container-low": "#111827",
          "on-tertiary-container": "#fff1eb",
          "success-bg": "#063626",
          "on-background": "#E5E7EB",
          "tertiary-fixed": "#ffdbcb",
          "pink": "#EC4899",
          "surface-container-highest": "#263448",
          "background": "#0B1120",
          "tertiary-fixed-dim": "#ffb692",
          "secondary-fixed-dim": "#ffb3ad",
          "error": "#ba1a1a",
          "danger": "#F87171",
          "accent-soft": "#16213B",
          "on-primary-fixed": "#DBEAFE",
          "on-surface-variant": "#CBD5E1",
          "purple-bg": "#241A3A",
          "on-secondary-fixed-variant": "#930013",
          "surface-bright": "#111827",
          "surface-container-high": "#202B3D",
          "on-tertiary-fixed": "#341100",
          "on-primary-fixed-variant": "#0031c4",
          "purple": "#A78BFA",
          "text-secondary": "#CBD5E1",
          "surface-tint": "#2e4edc",
          "text-muted": "#94A3B8",
          "outline": "#64748B",
          "surface-variant": "#1E293B",
          "on-error-container": "#93000a",
          "text-primary": "#F8FAFC",
          "secondary": "#b61722",
          "outline-variant": "#334155",
          "tertiary": "#933c00",
          "on-error": "#ffffff",
          "surface-dim": "#0F172A",
          "accent-hover": "#93B4FF",
          "inverse-surface": "#E5E7EB",
          "on-primary": "#ffffff",
          "danger-bg": "#3F1518",
          "primary-container": "#AFC4FF",
          "secondary-fixed": "#ffdad7",
          "on-secondary-container": "#fffbff",
          "warning-bg": "#3D2D08",
          "page-bg": "#0B1120",
          "warning": "#FBBF24",
          "primary-fixed": "#dee1ff",
          "surface": "#111827",
          "error-container": "#3F1518",
          "surface-container-lowest": "#0B1120",
          "secondary-container": "#da3437",
          "tertiary-container": "#ba4e00",
          "on-surface": "#F8FAFC",
          "inverse-on-surface": "#111827"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "topbar-height": "64px",
          "inline-gap": "10px",
          "card-padding": "20px",
          "stack-gap": "12px",
          "sidebar-width": "240px",
          "container-padding": "24px"
      },
      "fontFamily": {
          "body-lg": ["Poppins"],
          "display-lg": ["Poppins"],
          "label-sm": ["Poppins"],
          "label-md": ["Poppins"],
          "display-md": ["Poppins"],
          "body-md": ["Poppins"],
          "headline-sm": ["Poppins"]
      },
      "fontSize": {
          "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "display-lg": ["30px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "label-sm": ["11px", { "lineHeight": "1", "fontWeight": "600" }],
          "label-md": ["13px", { "lineHeight": "1", "fontWeight": "500" }],
          "display-md": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
          "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
